// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fitnes.Domain.Models.Fitnes;
using fitnes.Infrastructure.Persistence.Context;

#nullable disable

namespace fitnes.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915004238_AddMealEntries")]
    partial class AddMealEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("fitnes.Domain.Entities.MealEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AnalysisResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_result_id");

                    b.Property<DateTime>("ConsumedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId")
                        .IsUnique();

                    b.HasIndex("UserId", "ConsumedAt")
                        .IsDescending(false, true);

                    b.ToTable("meal_entries", (string)null);
                });

            modelBuilder.Entity("fitnes.Domain.Entities.MealEntryAverageView", b =>
                {
                    b.Property<double?>("AvgCalories")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_calories");

                    b.Property<double?>("AvgCarbs")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_carbs");

                    b.Property<double?>("AvgFat")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_fat");

                    b.Property<double?>("AvgProtein")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_protein");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<string>("DishName")
                        .HasColumnType("text")
                        .HasColumnName("dish_name");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("meal_entry_averages", (string)null);
                });

            modelBuilder.Entity("fitnes.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("fitnes.Domain.Models.Fitnes.FoodAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Analysis_Summary")
                        .HasColumnType("text")
                        .HasColumnName("analysis_summary");

                    b.Property<double>("Confidence_Score")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_score");

                    b.Property<string>("Dish_Name")
                        .HasColumnType("text")
                        .HasColumnName("dish_name");

                    b.Property<Nutrition>("Nutrition")
                        .HasColumnType("jsonb")
                        .HasColumnName("nutrition");

                    b.HasKey("Id");

                    b.ToTable("food_analysis_results", (string)null);
                });

            modelBuilder.Entity("fitnes.Domain.Entities.MealEntry", b =>
                {
                    b.HasOne("fitnes.Domain.Models.Fitnes.FoodAnalysisResult", "AnalysisResult")
                        .WithOne()
                        .HasForeignKey("fitnes.Domain.Entities.MealEntry", "AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("fitnes.Domain.Entities.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");

                    b.Navigation("User");
                });

            modelBuilder.Entity("fitnes.Domain.Models.Fitnes.FoodAnalysisResult", b =>
                {
                    b.OwnsOne("fitnes.Domain.Models.Fitnes.Serving", "Serving", b1 =>
                        {
                            b1.Property<Guid>("FoodAnalysisResultId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("serving_description");

                            b1.Property<string>("Unit")
                                .HasColumnType("text")
                                .HasColumnName("serving_unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("serving_value");

                            b1.HasKey("FoodAnalysisResultId");

                            b1.ToTable("food_analysis_results");

                            b1.WithOwner()
                                .HasForeignKey("FoodAnalysisResultId");
                        });

                    b.Navigation("Serving");
                });

            modelBuilder.Entity("fitnes.Domain.Entities.User", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
